### PR TITLE
Abandon package

### PR DESCRIPTION
**Pull request by nicolas-grekas**
Let's leverage https://github.com/symfony/flex/pull/409 instead, that will remove some complexity in our releasing processes.

### CODE REVIEW

**Comment by Nyholm** [comment]
I use this package when testing third party libraries on Travis. See https://github.com/symfony/psr-http-message-bridge/blob/master/.travis.yml#L41

Could/Should I really use flex for that?

**Comment by nicolas-grekas** [comment]
Yes, see  symfony/flex#409 and https://github.com/symfony/symfony/pull/28199

**Comment by keradus** [comment]
My case is exactly same as @Nyholm .

from DX perspective, it's easier to set up `force/lowest` package as dependency and all done, vs require flex, configure it and set `SYMFONY_ENDPOINT` env var :(

**Comment by nicolas-grekas** [comment]
Great, so you would just need to `composer global require --no-scripts symfony/flex` in your CI and `export SYMFONY_REQUIRE=~4.1.0` instead. I don't see any DX issue here. force-lowest and lts packages are far from being trivial to use actually, they're much more difficult to work with correctly.
And the maintaince burden doesn't justify keeping them.

**Pull request merged**
